/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function add(a: number, b: number): number

export declare function arrayDataF32(handle: number, out: Float32Array): number

export declare function arrayEval(handle: number): void

export declare function arrayNbytes(handle: number): number

export declare function arrayShape(handle: number): Array<number>

export declare function arraySize(handle: number): number

/**
 * Compile a precompiled ComputeImage runtime artifact from a source model directory.
 * Outputs manifest.json, receipt.json, and execution-ordered segment files.
 */
export declare function compileImage(sourceDir: string, outputDir: string): string

export declare function createArrayF32(data: Float32Array, shape: Array<number>): number

export declare function createArrayRaw(data: Buffer, shape: Array<number>, dtypeId: number): number

export declare function createScalarF32(value: number): number

export declare function detectDefaultDevice(): any

export declare function drainArrays(): void

export declare function freeArray(handle: number): void

export declare function gemma412BConfig(): string

export declare function gemmaForward(inputIds: Buffer, wh: string, kv: number): number

export declare function gemmaSampleGreedy(inputIds: Buffer, wh: string, kv: number): number

export declare function handleCount(): number

export declare function inspectSafetensors(path: string): string

export declare function loadSafetensors(path: string): string

export declare function matmul(a: number, b: number): number

/** Returns MLX Metal active memory in bytes, or 0 if unavailable. */
export declare function mlxActiveMemory(): number

/** Clear the MLX Metal allocator cache. Returns bytes freed. */
export declare function mlxClearCache(): number

export declare function multiply(a: number, b: number): number

/** Return the native dependency identity and capability report. */
export declare function nativeCapabilityReport(): string

export declare function parseConfigOnly(configPath: string): string

export declare function readCompiledImage(imageDir: string): string

/**
 * Execute the full 48-layer model from a compiled ComputeImage.
 * Returns the next token ID directly — no logits cross the FFI boundary.
 */
export declare function runFullModelFromImage(imageDir: string, inputIds: Buffer): number

export declare function validateFromMetadata(configPath: string, shardJsons: string): string

export declare function verifyCompiledImage(imageDir: string): string
